### ISSUE TITLE
CommentMailer is missing in setup

### ISSUE THREAD

**Issue by DominicBreuker** [HitFox/foxinator-generator#31]
Our Admin interface has a hidden feature: write as a comment _"admin@example.com is a super cool guy"_ and if an admin with email admin@example.com exists, he will be notified via email that he was mentioned in a comment.

Well, that works of course only if we include the "CommentMailer" into the project upon setup, which seems to be missing. When setting up a new app, we must add the following files:

'app/mailers/comment_mailer'

``` ruby
class CommentMailer < ApplicationMailer
  def admin_mention(comment)
    @comment = comment
    mail(to: @comment.admins.pluck(:email), subject: t('.subject'))
  end 
end
```

'app/views/comment_mailer/admin_mention.html.haml'

``` haml
%pre= @comment.message.html_safe
%br
= link_to t('.comment_link'), admin_admin_url(@comment.commentable, locale: I18n.locale), target: :blank
```

then add to the translations:

``` yaml
en:
  comment_mailer:
    admin_mention:
      comment_link: Take me to the comment
      subject: You were mentioned in a comment
```
